version: '3.9'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: maladies_swagger
    ports:
      - "8002:8080"
    environment:
      SWAGGER_JSON: /swagger/swagger.yaml
    volumes:
      - ./swagger:/swagger